# Generated by Django 3.1.1 on 2020-10-11 10:47

import account.managers
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('surname', models.CharField(max_length=30, verbose_name='Surname')),
                ('birthdate', models.DateField(verbose_name='Birthdate')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('passport', models.CharField(max_length=255, unique=True, verbose_name='Passport ID')),
                ('language', models.CharField(choices=[('EN', 'English'), ('RU', 'Russian'), ('TR', 'Turkish'), ('AZ', 'Azerbaijan')], default='EN', max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=50)),
                ('height', models.IntegerField()),
                ('blood_group', models.CharField(choices=[('A RH+', 'A RH+'), ('A RH-', 'A RH-'), ('AB RH+', 'AB RH+'), ('AB RH-', 'AB RH-'), ('B RH+', 'B RH+'), ('B RH-', 'B RH-'), ('0 RH+', '0 RH+'), ('0 RH-', '0 RH-')], default='A RH+', max_length=50)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('physical_activity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=50)),
                ('smoking', models.CharField(choices=[('Non-smoker', 'Non-smoker'), ('Ex-smoker', 'Ex-smoker'), ('Light-smoker', 'Light smoker (less than 10)'), ('Moderate-smoker', 'Light smoker (10 to 19)'), ('Heavy-smoker', 'Light smoker (20 or over)')], default='Non-smoker', max_length=50)),
                ('diabets', models.CharField(choices=[('None', 'None'), ('Type 1', 'Type 1'), ('Type 2', 'Type 2')], default='None', max_length=50)),
                ('ethnicity', models.CharField(choices=[('White', 'White or not stated'), ('Indian', 'Indian'), ('Pakistani', 'Pakistani'), ('Bangladeshi', 'Bangladeshi'), ('Asian', 'Other Asian'), ('Caribbean', 'Black Caribbean'), ('African', 'White or not stated'), ('African', 'Black African'), ('Chinese', 'Chinese'), ('Others', 'Others')], default='White', max_length=50)),
                ('angina_or_heart_attack', models.BooleanField()),
                ('menopause', models.BooleanField()),
                ('kidney_disease', models.BooleanField()),
                ('atrial_fibrillation', models.BooleanField()),
                ('pressure_treatment', models.BooleanField()),
                ('rheumatoid_arthritis', models.BooleanField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', account.managers.UserManager()),
            ],
        ),
    ]
