# Generated by Django 3.1.1 on 2020-10-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20201011_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='smoking',
            field=models.CharField(choices=[('Non-smoker', 'Non-smoker'), ('Ex-smoker', 'Ex-smoker'), ('Light-smoker', 'Light smoker (less than 10)'), ('Moderate-smoker', 'Moderate smoker (10 to 19)'), ('Heavy-smoker', 'Heavy smoker (20 or over)')], default='Non-smoker', max_length=50, null=True),
        ),
    ]
