# Generated by Django 3.1.1 on 2020-10-23 11:41

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20201011_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(max_length=255, null=True, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='user',
            name='town',
            field=models.CharField(max_length=255, null=True, verbose_name='Town/Village'),
        ),
        migrations.AlterField(
            model_name='user',
            name='angina_or_heart_attack',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='ANGINA OR HEART ATTACK IN A 1ST DEGREE RELATIVE &lt;60?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='atrial_fibrillation',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='Arterial Fibrillation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A RH+', 'A RH+'), ('A RH-', 'A RH-'), ('AB RH+', 'AB RH+'), ('AB RH-', 'AB RH-'), ('B RH+', 'B RH+'), ('B RH-', 'B RH-'), ('0 RH+', '0 RH+'), ('0 RH-', '0 RH-')], default='A RH+', max_length=50, null=True, verbose_name='Blood Group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='diabets',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Type 1', 'Type 1'), ('Type 2', 'Type 2')], default='None', max_length=50, null=True, verbose_name='Diabets'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ethnicity',
            field=models.CharField(choices=[('White', 'White or not stated'), ('Indian', 'Indian'), ('Pakistani', 'Pakistani'), ('Bangladeshi', 'Bangladeshi'), ('Asian', 'Other Asian'), ('Caribbean', 'Black Caribbean'), ('African', 'Black African'), ('Chinese', 'Chinese'), ('Others', 'Others')], default='White', max_length=50, null=True, verbose_name='Ethnicity'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=50, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.IntegerField(null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kidney_disease',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='Kidney Disease'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('RU', 'Russian'), ('TR', 'Turkish'), ('AZ', 'Azerbaijan')], default='EN', max_length=50, null=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='menopause',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='Menopause'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='User ID(Citizen ID or E-mail or Mobile number)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='physical_activity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=50, null=True, verbose_name='Physical Activity'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pressure_treatment',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='DO YOU GETTING PRESSURE TREATMENT?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rheumatoid_arthritis',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='Rheumatoid Arthritis'),
        ),
        migrations.AlterField(
            model_name='user',
            name='smoking',
            field=models.CharField(blank=True, choices=[('Non-smoker', 'Non-smoker'), ('Ex-smoker', 'Ex-smoker'), ('Light-smoker', 'Light smoker (less than 10)'), ('Moderate-smoker', 'Moderate smoker (10 to 19)'), ('Heavy-smoker', 'Heavy smoker (20 or over)')], default='Non-smoker', max_length=50, null=True, verbose_name='Smoking'),
        ),
    ]
