# Generated by Django 3.1.3 on 2020-11-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20201103_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Card number'),
        ),
    ]
