# Generated by Django 3.1.3 on 2020-11-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20201104_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=255, null=True, verbose_name='Country'),
        ),
    ]
