# Generated by Django 3.1.3 on 2021-01-03 11:37

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(max_length=50, null=True)),
                ('cat_name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('tr', 'Turkish'), ('az', 'Azerbaijan')], default='en', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=250)),
                ('subtitle', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('img', models.CharField(max_length=250)),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('tr', 'Turkish'), ('az', 'Azerbaijan')], default='en', max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
    ]
