from django.utils.translation import ugettext_lazy as _


BOOL_CHOICES = ((True, _('Yes')), (False, _('No')))


ENGLISH_LANG = 'EN'
RUSSIAN_LANG = 'RU'
TURKISH_LANG = 'TR'
AZERBAIJANI_LANG = 'AZ'
LANGUAGE_CHOICES = [
    (ENGLISH_LANG, _('English')),
    (RUSSIAN_LANG, _('Russian')),
    (TURKISH_LANG, _('Turkish')),
    (AZERBAIJANI_LANG, _('Azerbaijan')),
]


MALE_GENDER = 'male'
FEMALE_GENDER = 'female'
GENDER_CHOICES = [
    (MALE_GENDER, _('Male')),
    (FEMALE_GENDER, _('Female')),
]

A_PLUS = 'A RH+'
A_MINUS = 'A RH-'
AB_PLUS = 'AB RH+'
AB_MINUS = 'AB RH-'
B_PLUS = 'B RH+'
B_MINUS = 'B RH-'
ZERO_PLUS = '0 RH+'
ZERO_MINUS = '0 RH-'
BLOOD_GROUP_CHOICES = [
    (A_PLUS, A_PLUS),
    (A_MINUS, A_MINUS),
    (AB_PLUS, AB_PLUS),
    (AB_MINUS, AB_MINUS),
    (B_PLUS, B_PLUS),
    (B_MINUS, B_MINUS),
    (ZERO_PLUS, ZERO_PLUS),
    (ZERO_MINUS, ZERO_MINUS),
]


ACTIVITY_LOW = _('Low')
ACTIVITY_MEDIUM = _('Medium')
ACTIVITY_HIGH = _('High')
PHYSICAL_ACTIVITY_CHOICES = [
    (ACTIVITY_LOW, ACTIVITY_LOW),
    (ACTIVITY_MEDIUM, ACTIVITY_MEDIUM),
    (ACTIVITY_HIGH, ACTIVITY_HIGH),
]

SMOKER_NON = _('Non-smoker')
SMOKER_EX = _('Ex-smoker')
SMOKER_LIGHT = _('Light-smoker')
SMOKER_MODERATE = _('Moderate-smoker')
SMOKER_HEAVY = _('Heavy-smoker')
SMOKING_CHOICES = [
    (SMOKER_NON, SMOKER_NON),
    (SMOKER_EX, SMOKER_EX),
    (SMOKER_LIGHT, _('Light smoker (less than 10)')),
    (SMOKER_MODERATE, _('Moderate smoker (10 to 19)')),
    (SMOKER_HEAVY, _('Heavy smoker (20 or over)')),
]

DIABET_TYPE_NONE = _('None')
DIABET_TYPE_ONE = _('Type 1')
DIABET_TYPE_TWO = _('Type 2')
DIABETS_CHOICES = [
    (DIABET_TYPE_NONE, DIABET_TYPE_NONE),
    (DIABET_TYPE_ONE, DIABET_TYPE_ONE),
    (DIABET_TYPE_TWO, DIABET_TYPE_TWO),
]

ETHNICITY_WHITE = _('White')
ETHNICITY_INDIAN = _('Indian')
ETHNICITY_PAKISTANI = _('Pakistani')
ETHNICITY_BANGLADESHI = _('Bangladeshi')
ETHNICITY_OTHER_ASIAN = _('Asian')
ETHNICITY_BLACK_CARIBBEAN = _('Caribbean')
ETHNICITY_BLACK_AFRICAN = _('African')
ETHNICITY_CHINESE = _('Chinese')
ETHNICITY_OTHERS = _('Others')
ETHNICITY_CHOICES = [
    (ETHNICITY_WHITE, _('White or not stated')),
    (ETHNICITY_INDIAN, ETHNICITY_INDIAN),
    (ETHNICITY_PAKISTANI, ETHNICITY_PAKISTANI),
    (ETHNICITY_BANGLADESHI, ETHNICITY_BANGLADESHI),
    (ETHNICITY_OTHER_ASIAN, _('Other Asian')),
    (ETHNICITY_BLACK_CARIBBEAN, _('Black Caribbean')),
    (ETHNICITY_BLACK_AFRICAN, _('Black African')),
    (ETHNICITY_CHINESE, ETHNICITY_CHINESE),
    (ETHNICITY_OTHERS, ETHNICITY_OTHERS),
]